FROM ojooss/phpliteadmin AS sqliteadmin

RUN addgroup --gid 1000 appuser
RUN adduser --uid 1000 --gid 1000 --disabled-password appuser
RUN adduser www-data appuser

ENV ACCEPT_EULA=Y
ENV APACHE_ROOT_DIR=/var/www/html
ENV APACHE_DOCUMENT_ROOT=/var/www/html
ENV APACHE_LOG_DIR=/var/log
ENV APACHE_RUN_USER=appuser
ENV APACHE_RUN_GROUP=appuser

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
        zip \
        unzip \
        vim \
        curl \
        apache2-utils \
        wget \
        libpcre3 \
        apt-utils \
        xvfb \
        sqlite3 \
        sqlite3-pcre \
        libfontconfig \
        gnupg 

RUN apt-get -y autoremove \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

EXPOSE 80

USER appuser

WORKDIR /var/www/html/dbs
